In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('Grades.csv')
df.tail(10)

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
561,CS-97562,B-,B,A-,B+,B-,B+,A-,A,B,...,B+,B-,B+,D+,C+,B-,B+,C,C+,2.828
562,CS-97563,B,B,A,C,B,B+,B,C-,B+,...,A-,B,B+,B+,B+,C+,A-,D+,C+,2.821
563,CS-97564,A-,B,A,D+,B+,A-,C,A,C+,...,B+,C,B+,C-,C-,C,F,D,C,2.612
564,CS-97565,A-,D,A,C,B+,B+,C,A-,B-,...,B,C+,B+,D+,C,C-,B,C,B-,2.607
565,CS-97566,F,F,D,C-,NaN,D+,D,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.800
566,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
567,CS-97568,A+,A,A,A,A,A,A,A-,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
568,CS-97569,B,A,A-,B+,A,A,A,A,A,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
569,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,D,B,B,C-,D,C,B,B-,C,2.193
570,CS-97571,C,D,D,C,C,D+,B,C+,C,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

In [3]:
df.isnull().sum()

Seat No.      0
PH-121        0
HS-101        0
CY-105        1
HS-105/12     1
MT-111        2
CS-105        0
CS-106        2
EL-102        2
EE-119        2
ME-107        2
CS-107        2
HS-205/20     5
MT-222        5
EE-222        7
MT-224        7
CS-210        7
CS-211        5
CS-203        5
CS-214        6
EE-217        6
CS-212        6
CS-215        6
MT-331        9
EF-303       10
HS-304       10
CS-301       10
CS-302       10
TC-383       10
MT-442       10
EL-332        9
CS-318        9
CS-306        9
CS-312       10
CS-317       12
CS-403       12
CS-421       12
CS-406       85
CS-414       13
CS-419       13
CS-423       14
CS-412       79
CGPA          0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 43 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Seat No.   571 non-null    object
 1   PH-121     571 non-null    object
 2   HS-101     571 non-null    object
 3   CY-105     570 non-null    object
 4   HS-105/12  570 non-null    object
 5   MT-111     569 non-null    object
 6   CS-105     571 non-null    object
 7   CS-106     569 non-null    object
 8   EL-102     569 non-null    object
 9   EE-119     569 non-null    object
 10  ME-107     569 non-null    object
 11  CS-107     569 non-null    object
 12  HS-205/20  566 non-null    object
 13  MT-222     566 non-null    object
 14  EE-222     564 non-null    object
 15  MT-224     564 non-null    object
 16  CS-210     564 non-null    object
 17  CS-211     566 non-null    object
 18  CS-203     566 non-null    object
 19  CS-214     565 non-null    object
 20  EE-217     565 non-null    object
 21  CS-212     565 non-null    object
 22  CS-215     565 non-null    object
 23  MT-331     562 non-null    object
 24  EF-303     561 non-null    object
 25  HS-304     561 non-null    object
 26  CS-301     561 non-null    object
 27  CS-302     561 non-null    object
 28  TC-383     561 non-null    object
 29  MT-442     561 non-null    object
 30  EL-332     562 non-null    object
 31  CS-318     562 non-null    object
 32  CS-306     562 non-null    object
 33  CS-312     561 non-null    object
 34  CS-317     559 non-null    object
 35  CS-403     559 non-null    object
 36  CS-421     559 non-null    object
 37  CS-406     486 non-null    object
 38  CS-414     558 non-null    object
 39  CS-419     558 non-null    object
 40  CS-423     557 non-null    object
 41  CS-412     492 non-null    object
 42  CGPA       571 non-null    float64
dtypes: float64(1), object(42)
memory usage: 191.9+ KB

In [5]:
df_col=df[['PH-121', 'HS-101', 'CY-105', 'HS-105/12', 'MT-111',
       'CS-105', 'CS-106', 'EL-102', 'EE-119', 'ME-107', 'CS-107', 'HS-205/20',
       'MT-222', 'EE-222', 'MT-224', 'CS-210', 'CS-211', 'CS-203', 'CS-214',
       'EE-217', 'CS-212', 'CS-215', 'MT-331', 'EF-303', 'HS-304', 'CS-301',
       'CS-302', 'TC-383', 'MT-442', 'EL-332', 'CS-318', 'CS-306', 'CS-312',
       'CS-317', 'CS-403', 'CS-421', 'CS-406', 'CS-414', 'CS-419', 'CS-423',
       'CS-412']]

In [6]:
Grades = pd.DataFrame(columns=["Feature", "Unique", "Nunique"])

for i in range(len(df_col.columns)):
    Grades.loc[i] = [df_col.columns[i]] + [df[df_col.columns[i]].unique()] + [df[df_col.columns[i]].nunique()]


Grades

# x = 1
# for column in df_col:
#     if x<=43:
#         print(df[column].value_counts(),'\n')
#         print(df[column].unique(),'\n')
        
#     x+=1

      Feature                                             Unique  Nunique
0      PH-121    [B-, A, D, A-, B+, B, C+, C, C-, D+, WU, A+, F]       13
1      HS-101        [D+, D, B, C+, A-, B-, C-, B+, C, A, A+, F]       12
2      CY-105  [C-, D+, A, A-, B, C+, B+, B-, C, D, nan, WU, ...       13
3   HS-105/12  [C, D, B-, B+, D+, B, C-, C+, A-, A, nan, WU, ...       13
4      MT-111  [C-, B-, B+, D, A, C+, A-, C, B, D+, nan, A+, ...       13
5      CS-105           [D+, C, A, A-, B, B-, B+, C+, C-, A+, D]       11
6      CS-106  [D, B-, D+, A-, C+, A, C-, C, B, B+, nan, A+, ...       13
7      EL-102  [C-, A, B+, B, A-, B-, C, C+, D+, D, nan, A+, ...       13
8      EE-119  [B-, D+, A-, D, A, B+, B, C-, C+, C, WU, nan, A+]       12
9      ME-107  [C-, D, A-, C+, B+, A, D+, C, B, B-, WU, nan, ...       13
10     CS-107  [C-, B+, B-, D, C, A-, C+, D+, B, A, nan, A+, ...       14
11  HS-205/20  [B+, C+, A-, B, A, B-, nan, D, WU, A+, C, D+, ...       13
12     MT-222  [D, B-, A, D+, C, B+, A-, B, C+, nan, C-, WU, ...       14
13     EE-222  [A-, C-, A, B-, B+, C+, D+, B, nan, C, W, A+, ...       13
14     MT-224  [B-, D+, A, D, A-, C-, C, B+, C+, B, nan, A+, ...       14
15     CS-210  [C+, D+, A, C, A-, B+, B-, B, nan, D, A+, C-, ...       14
16     CS-211  [D+, D, A+, B+, B-, B, A-, C-, C+, C, nan, A, ...       14
17     CS-203  [D+, C, A, C+, A-, B+, B, B-, C-, nan, D, A+, ...       13
18     CS-214  [D, A-, B, C, B-, C+, A, C-, B+, D+, nan, I, F...       13
19     EE-217  [A, B-, D+, A-, A+, C, B+, B, nan, C-, D, WU, ...       13
20     CS-212  [D, C, A-, C+, B-, D+, B+, B, A, C-, nan, A+, WU]       12
21     CS-215  [C-, D, A, A-, C+, C, B+, B-, D+, nan, B, A+, ...       14
22     MT-331   [C, D+, A, C+, B+, A-, B, B-, A+, D, C-, nan, F]       12
23     EF-303   [C-, D, C+, B+, C, D+, A-, B-, A, nan, B, WU, F]       12
24     HS-304  [C+, C-, A, B-, A-, B+, B, nan, C, D, D+, A+, ...       14
25     CS-301   [B, A-, B+, D, B-, D+, C, C+, C-, A, nan, F, A+]       12
26     CS-302      [C, D+, A-, B-, C+, B, D, B+, A, nan, C-, A+]       11
27     TC-383   [C+, C-, B, D+, C, B+, B-, D, A-, A, nan, F, A+]       12
28     MT-442   [B+, C-, A, A-, B, A+, C+, nan, B-, C, D+, D, F]       12
29     EL-332  [C, B+, D+, A-, B, A, B-, C-, C+, nan, D, A+, ...       13
30     CS-318  [C-, A-, B+, B-, C, B, C+, D, D+, A, nan, A+, ...       14
31     CS-306  [C, D, A-, C-, B+, C+, B-, B, A, D+, nan, A+, ...       13
32     CS-312  [C-, D+, B, B-, C, B+, C+, A-, D, nan, A, F, A...       14
33     CS-317   [C-, D, B, C, B+, B-, A-, D+, C+, nan, A, A+, F]       12
34     CS-403      [C-, C, A, D+, B+, C+, B-, A-, B, nan, A+, D]       11
35     CS-421  [C-, D, C, B-, C+, B+, D+, B, nan, A, A-, F, A...       13
36     CS-406  [A-, A, B-, B, B+, nan, C+, D, D+, C-, C, A+, ...       14
37     CS-414  [A, B-, B, A-, B+, A+, C, nan, C-, C+, F, D+, ...       13
38     CS-419   [C-, C, A, C+, A-, B+, B-, B, nan, D+, A+, D, F]       12
39     CS-423   [B, C, A-, C+, B-, B+, C-, A, D+, nan, D, A+, F]       12
40     CS-412  [A-, B, A, C+, B+, C-, B-, nan, A+, C, D+, F, ...       13

As per the observation all columns have grades categorical as, A+,A,A-,B+,B,B-,C+,C,C-,D+,D,F,W,WU,I.

1. "W”(Withdrawal) indicates that the student was permitted to drop the course.
    It carries no connotation of quality of student performance and is not used in the calculation of CGPA.
    that's way drop those rows which have "W" grade.

2. "WU"(Withdrawal Unauthorized) and "I"(Incomplete), progress point computation is equivalent to an “F”
    Replace all "F","WU","I" with 0 value.

3. Have to convert all Grades means categorical data to numerical data.

In [7]:
# Drop the Withdrawal grades rows, which are not used in the calculation of CGPA.

for i in df.columns:
    df.drop(df[df.loc[:,i]=='W'].index,inplace=True)

df.reset_index(drop=True, inplace=True)
df

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
0,CS-97001,B-,D+,C-,C,C-,D+,D,C-,B-,...,C-,C-,C-,C-,A-,A,C-,B,A-,2.205
1,CS-97002,A,D,D+,D,B-,C,D,A,D+,...,D+,D,C,D,A-,B-,C,C,B,2.008
2,CS-97003,A,B,A,B-,B+,A,B-,B+,A-,...,B,B,A,C,A,A,A,A-,A,3.608
3,CS-97004,D,C+,D+,D,D,A-,D+,C-,D,...,D+,C,D+,C-,B-,B,C+,C+,C+,1.906
4,CS-97005,A-,A-,A-,B+,A,A,A-,B+,A,...,B-,B+,B+,B-,A-,A,A-,A-,A,3.448
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,CS-97567,B,A,A,A-,A+,A,A-,A-,A+,...,A-,A-,A,A,A,B+,B+,B,A,3.798
554,CS-97568,A+,A,A,A,A,A,A,A-,A,...,B+,B+,A,A,A-,B,A-,C,A-,3.772
555,CS-97569,B,A,A-,B+,A,A,A,A,A,...,A-,B,A,B+,A,C,B+,A-,A-,3.470
556,CS-97570,A,B+,D,A,D,D+,B-,C-,B-,...,D,B,B,C-,D,C,B,B-,C,2.193
557,CS-97571,C,D,D,C,C,D+,B,C+,C,...,C+,C,B-,D,F,C-,B+,D,C-,1.753

#  Replacing Grades with quivalent scale.

In [8]:
for i in df.columns:
    df[i] = df[i].replace('A+',4.0)
    df[i] = df[i].replace('A',3.8)
    df[i] = df[i].replace('A-',3.7)
    df[i] = df[i].replace('B+',3.3)
    df[i] = df[i].replace('B',3.0)
    df[i] = df[i].replace('B-',2.7)
    df[i] = df[i].replace('C+',2.3)
    df[i] = df[i].replace('C',2.0)
    df[i] = df[i].replace('C-',1.7)
    df[i] = df[i].replace('D+',1.3)
    df[i] = df[i].replace('D',1.0)
    df[i] = df[i].replace('F',0.0)
    df[i] = df[i].replace('WU',0.0)
    df[i] = df[i].replace('I',0.0)
     
df.tail(10)

,Seat No.,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,...,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412,CGPA
548,CS-97562,2.7,3.0,3.7,3.3,2.7,3.3,3.7,3.8,3.0,...,3.3,2.7,3.3,1.3,2.3,2.7,3.3,2.0,2.3,2.828
549,CS-97563,3.0,3.0,3.8,2.0,3.0,3.3,3.0,1.7,3.3,...,3.7,3.0,3.3,3.3,3.3,2.3,3.7,1.3,2.3,2.821
550,CS-97564,3.7,3.0,3.8,1.3,3.3,3.7,2.0,3.8,2.3,...,3.3,2.0,3.3,1.7,1.7,2.0,0.0,1.0,2.0,2.612
551,CS-97565,3.7,1.0,3.8,2.0,3.3,3.3,2.0,3.7,2.7,...,3.0,2.3,3.3,1.3,2.0,1.7,3.0,2.0,2.7,2.607
552,CS-97566,0.0,0.0,1.0,1.7,NaN,1.3,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.800
553,CS-97567,3.0,3.8,3.8,3.7,4.0,3.8,3.7,3.7,4.0,...,3.7,3.7,3.8,3.8,3.8,3.3,3.3,3.0,3.8,3.798
554,CS-97568,4.0,3.8,3.8,3.8,3.8,3.8,3.8,3.7,3.8,...,3.3,3.3,3.8,3.8,3.7,3.0,3.7,2.0,3.7,3.772
555,CS-97569,3.0,3.8,3.7,3.3,3.8,3.8,3.8,3.8,3.8,...,3.7,3.0,3.8,3.3,3.8,2.0,3.3,3.7,3.7,3.470
556,CS-97570,3.8,3.3,1.0,3.8,1.0,1.3,2.7,1.7,2.7,...,1.0,3.0,3.0,1.7,1.0,2.0,3.0,2.7,2.0,2.193
557,CS-97571,2.0,1.0,1.0,2.0,2.0,1.3,3.0,2.3,2.0,...,2.3,2.0,2.7,1.0,0.0,1.7,3.3,1.0,1.7,1.753

# Now Separting columns into features and target

In [9]:
x=df.drop(columns=['Seat No.','CGPA'])
y=df.CGPA

# Now handle null values

In [10]:
x = x.fillna(round (x.mean(),1))
x.tail(10)

,PH-121,HS-101,CY-105,HS-105/12,MT-111,CS-105,CS-106,EL-102,EE-119,ME-107,...,CS-306,CS-312,CS-317,CS-403,CS-421,CS-406,CS-414,CS-419,CS-423,CS-412
548,2.7,3.0,3.7,3.3,2.7,3.3,3.7,3.8,3.0,3.0,...,1.0,3.3,2.7,3.3,1.3,2.3,2.7,3.3,2.0,2.3
549,3.0,3.0,3.8,2.0,3.0,3.3,3.0,1.7,3.3,3.3,...,2.7,3.7,3.0,3.3,3.3,3.3,2.3,3.7,1.3,2.3
550,3.7,3.0,3.8,1.3,3.3,3.7,2.0,3.8,2.3,2.0,...,1.7,3.3,2.0,3.3,1.7,1.7,2.0,0.0,1.0,2.0
551,3.7,1.0,3.8,2.0,3.3,3.3,2.0,3.7,2.7,1.0,...,1.7,3.0,2.3,3.3,1.3,2.0,1.7,3.0,2.0,2.7
552,0.0,0.0,1.0,1.7,3.0,1.3,1.0,2.9,3.0,2.7,...,2.9,2.9,2.7,3.1,2.5,3.3,3.4,3.0,2.9,3.2
553,3.0,3.8,3.8,3.7,4.0,3.8,3.7,3.7,4.0,3.3,...,3.3,3.7,3.7,3.8,3.8,3.8,3.3,3.3,3.0,3.8
554,4.0,3.8,3.8,3.8,3.8,3.8,3.8,3.7,3.8,3.8,...,3.7,3.3,3.3,3.8,3.8,3.7,3.0,3.7,2.0,3.7
555,3.0,3.8,3.7,3.3,3.8,3.8,3.8,3.8,3.8,3.0,...,3.3,3.7,3.0,3.8,3.3,3.8,2.0,3.3,3.7,3.7
556,3.8,3.3,1.0,3.8,1.0,1.3,2.7,1.7,2.7,1.7,...,3.3,1.0,3.0,3.0,1.7,1.0,2.0,3.0,2.7,2.0
557,2.0,1.0,1.0,2.0,2.0,1.3,3.0,2.3,2.0,1.3,...,1.3,2.3,2.0,2.7,1.0,0.0,1.7,3.3,1.0,1.7

Now the dataset is ready for make a model, bcoz we all subject has it own coorelation with target,
that's way cannot use multicorelation method. 
Also we cannot remove any skeweness or outliers form dataset, so let's further for model.

# Model Development

In [11]:
#import the necessary model algos.
#regression
from sklearn.linear_model import LinearRegression,Ridge,Lasso,RidgeCV,LassoCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor,BaggingRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.svm import SVR

#model selection
from sklearn.model_selection import train_test_split,cross_validate,cross_val_score
from sklearn.model_selection import GridSearchCV

#preprocessing
from sklearn.preprocessing import StandardScaler

#evaluation metrics
from sklearn.metrics import mean_squared_log_error,mean_squared_error, r2_score,mean_absolute_error # for regression

In [12]:
LR = LinearRegression()
LSO= Lasso()
RIG= Ridge()
KNN= KNeighborsRegressor()
RF = RandomForestRegressor()
BAG= BaggingRegressor()
GRA= GradientBoostingRegressor()
ADA= AdaBoostRegressor()

In [13]:
model=[LinearRegression(), Lasso(), Ridge(), KNeighborsRegressor(), RandomForestRegressor(), BaggingRegressor(),
       GradientBoostingRegressor(), AdaBoostRegressor()]

models=['LR = LinearRegression()','LSO = Lasso()', 'RIG = Ridge()', 'KNN = KNeighborsRegressor()',
        'RF = RandomForestRegressor()', 'BAG = BaggingRegressor()', 'GRA = GradientBoostingRegressor()',
        'ADA = AdaBoostRegressor()']

acc_result=[]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=11)

for i in range(len(model)):
    clf=model[i]
    clf.fit(x_train,y_train)
    y_pred=clf.predict(x_test)
    acc_result.append(round (r2_score(y_pred,y_test)*100,2))

Result_df=pd.DataFrame({'Model Name':models, 'Accuracy Score (without tuning)':acc_result})
Result_df

                          Model Name  Accuracy Score (without tuning)
0            LR = LinearRegression()                            84.23
1                      LSO = Lasso()                             0.00
2                      RIG = Ridge()                            84.23
3        KNN = KNeighborsRegressor()                            78.42
4       RF = RandomForestRegressor()                            75.80
5           BAG = BaggingRegressor()                            72.05
6  GRA = GradientBoostingRegressor()                            82.51
7          ADA = AdaBoostRegressor()                            60.44

# Linear Regression

In [14]:
r2s_train=[]
r2s_test=[]

for i in range (0,100):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=i)
    
    lr = LinearRegression()
    lr.fit(x_train,y_train)
    
    x_lr_predict=lr.predict(x_train)
    y_lr_predict=lr.predict(x_test)
    
    r2s_train.append(r2_score(y_train,x_lr_predict))
    r2s_test.append(r2_score(y_test,y_lr_predict))

    
r2s_test_index= r2s_test.index(max(r2s_test))
print("Index of max vaule of test's R2 score at",r2s_test_index)
        
r2s_train_index= r2s_train.index(max(r2s_train))    
print("Index of max vaule of train's R2 score at",r2s_train_index)

Index of max vaule of test's R2 score at 23
Index of max vaule of train's R2 score at 14

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=23)
    
lr.fit(x_train,y_train)
x_lr_predict=lr.predict(x_train)
y_lr_predict=lr.predict(x_test)
    
print ("The training accurancy @ 23 state is:",r2_score(y_train,x_lr_predict))
print ("The testing accurancy @ 23 state is:",r2_score(y_test,y_lr_predict))

The training accurancy @ 23 state is: 0.9616319867063773
The testing accurancy @ 23 state is: 0.9897795099058773

In [16]:
#Cross-Validation of the Model


Train_accuracy=r2_score(y_train,x_lr_predict)
Test_accuracy =r2_score(y_test,y_lr_predict)

from sklearn.model_selection import cross_val_score

for i in range (2,10):
    cv_score = cross_val_score(lr,x,y,cv=i)
    cv_mean = cv_score.mean()
    print("At Cross fold", i, "the cv score is", cv_mean, "\n  accuracy score for training is", Train_accuracy,
          "\n& accuracy for testing is", Test_accuracy)
    print("\n")

At Cross fold 2 the cv score is 0.9122890911435262
  accuracy score for training is 0.9616319867063773
& accuracy for testing is 0.9897795099058773


At Cross fold 3 the cv score is 0.9339283636186427
  accuracy score for training is 0.9616319867063773
& accuracy for testing is 0.9897795099058773


At Cross fold 4 the cv score is 0.9032310919484396
  accuracy score for training is 0.9616319867063773
& accuracy for testing is 0.9897795099058773


At Cross fold 5 the cv score is 0.9548023595627495
  accuracy score for training is 0.9616319867063773
& accuracy for testing is 0.9897795099058773


At Cross fold 6 the cv score is 0.9533385326477029
  accuracy score for training is 0.9616319867063773
& accuracy for testing is 0.9897795099058773


At Cross fold 7 the cv score is 0.9581324648306422
  accuracy score for training is 0.9616319867063773
& accuracy for testing is 0.9897795099058773


At Cross fold 8 the cv score is 0.9536126279024613
  accuracy score for training is 0.9616319867063773
& accuracy for testing is 0.9897795099058773


At Cross fold 9 the cv score is 0.9573718797922237
  accuracy score for training is 0.9616319867063773
& accuracy for testing is 0.9897795099058773

# Lasso Regression

In [17]:
lasscv = LassoCV (alphas=None, max_iter= 100)
# normalize means sandarad scaled data
lasscv.fit(x_train,y_train)

LassoCV(max_iter=100)

In [18]:
# best alpha parameter
alpha = lasscv.alpha_
las = Lasso(alpha)
las.fit(x_train,y_train)
las.score(x_train,y_train)

0.9613343631259383

In [19]:
y_las_predict=las.predict(x_test)
r2_score(y_test,y_las_predict)

0.9909002581529152

In [20]:
cv_score=cross_val_score(las,x,y,cv=5)
cv_score.mean()

0.9551305197670283

# Ridge Regression

In [21]:
ridgecv = RidgeCV(alphas = np.arange(0.001,0.1,0.01), normalize = False)
ridgecv.fit(x_train,y_train)
alpha = ridgecv.alpha_

rig = Ridge (alpha)
rig.fit(x_train,y_train)
rig.score(x_train,y_train)

0.9616319788498143

In [22]:
y_rig_predict=rig.predict(x_test)
r2_score(y_test,y_rig_predict)

0.9897949130731033

In [23]:
cv_score=cross_val_score(rig,x,y,cv=5)
cv_score.mean()

0.9548183800973586

# KNeighbors Regressor

In [24]:
knn=KNeighborsRegressor(n_neighbors=10)
knn.fit(x_train,y_train)

y_knn_predict=knn.predict(x_test)
print('R2 Score:',r2_score(y_test,y_knn_predict))

cv_score=cross_val_score(knn,x,y,cv=5)
print ('Cross validation:',cv_score.mean())

R2 Score: 0.9561736738008879
Cross validation: 0.9268790897163773

# RandomForest Regression

In [25]:
rf=RandomForestRegressor(criterion='mse') #,"mae", "poisson"])

rf.fit(x_train,y_train)

y_rf_predict=rf.predict(x_test)
print('R2 Score:',r2_score(y_test,y_rf_predict))

cv_score=cross_val_score(rf,x,y,cv=5)
print ('Cross validation:',cv_score.mean())

R2 Score: 0.9609179738535011
Cross validation: 0.9279691579065565

In [26]:
Acc_Score_tun =[round (r2_score(y_test,y_lr_predict)*100,2),
                round (r2_score(y_test,y_las_predict)*100,2),
                round (r2_score(y_test,y_rig_predict)*100,2),
                round (r2_score(y_test,y_knn_predict)*100,2),
                round (r2_score(y_test,y_rf_predict)*100,2)]

stu_cgpa = pd.DataFrame({'Regressor':['lr = LinearRegression()', 'las = Lasso()','rig = Ridge()',
                                'knn = KNeighborsRegressor()' ,'rf = RandomForestRegressor()'],
                                 
                                'Accuracy Score (with tuning)':Acc_Score_tun})
stu_cgpa

                      Regressor  Accuracy Score (with tuning)
0       lr = LinearRegression()                         98.98
1                 las = Lasso()                         99.09
2                 rig = Ridge()                         98.98
3   knn = KNeighborsRegressor()                         95.62
4  rf = RandomForestRegressor()                         96.09

In [27]:
Stu_CGPA_Prediction= pd.concat([Result_df[0:5],stu_cgpa],axis=1)
Stu_CGPA_Prediction

,Model Name,Accuracy Score (without tuning),Regressor,Accuracy Score (with tuning)
0,LR = LinearRegression(),84.23,lr = LinearRegression(),98.98
1,LSO = Lasso(),0.00,las = Lasso(),99.09
2,RIG = Ridge(),84.23,rig = Ridge(),98.98
3,KNN = KNeighborsRegressor(),78.42,knn = KNeighborsRegressor(),95.62
4,RF = RandomForestRegressor(),75.80,rf = RandomForestRegressor(),96.09

# we are gettig model accuracy: 99% and cross validation: 95% which shows our model is performing exremely well using Liner Regression, Lasso Regression and Ridge Regression, so we can use any model among these three model.

# Save the model using pickle

In [28]:
import pickle
pickle.dump(las,open('STUDENT CGPA','wb'))